### ISSUE TITLE
Resolve Redis client deprecation warnings

### ISSUE THREAD

**Issue by lewispb** [rails/kredis#75]
There's quite a few of these warnings to be resolved:

```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.pipelined do
  redis.get("key")
end

should be replaced by

redis.pipelined do |pipeline|
  pipeline.get("key")
end

(called from /Users/lewis/work/rails/kredis/lib/kredis/migration.rb:46:in `each_key_batch_matching'}
```

**Comment by inem** [comment]
Having the same problem:

```
redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end

(called from /usr/src/app/vendor/bundle/ruby/3.0.0/gems/kredis-1.1.0/lib/kredis/types/proxy.rb:13:in `multi'}
```

**Comment by dhh** [comment]
We solved this with another pipeline change.
